version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL}
      - REACT_APP_SUPABASE_ANON_KEY=${REACT_APP_SUPABASE_ANON_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
